appName: my-web-service
track: production
replicaCount: 3
image:
  repository: ghcr.io/pohsiu/my-spinnaker-canary-app
  tag: stable
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  port: 3000
  type: ClusterIP
env: []
